name: contacts
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  call_log: ^4.0.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_contacts: ^1.1.8
  flutter_popup: ^3.3.0
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0
  google_fonts: ^6.2.1
  grouped_list: ^6.0.0
  hive: ^2.2.3
  intl: ^0.19.0
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
